RailsNotes/Rails_Exploration/Completed/file_db_app/config/routes.rb
Rails.application.routes.draw do
  resources :documents

	root 'documents#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

RailsNotes/Rails_Exploration/Completed/file_db_app/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

RailsNotes/Rails_Exploration/Completed/file_db_app/app/models/document.rb
class Document < ApplicationRecord
	# app/models/document.rb
	def initialize(params = {})
	  file = params.delete(:file)
	  super
	  if file
	    self.filename = sanitize_filename(file.original_filename)
	    self.content_type = file.content_type
	    self.file_contents = file.read
	  end
	end
	private
	  def sanitize_filename(filename)
	    # Get only the filename, not the whole path (for IE)
	    # Thanks to this article I just found for the tip: http://mattberther.com/2007/10/19/uploading-files-to-a-database-using-rails
	    return File.basename(filename)
	  end
		# Tutorial did not specify whether definitions inside model
		# Placed inside on my own
end

RailsNotes/Rails_Exploration/Completed/file_db_app/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

RailsNotes/Rails_Exploration/Completed/file_db_app/app/controllers/documents_controller.rb
class DocumentsController < ApplicationController
  before_action :set_document, only: [:show, :edit, :update, :destroy]

  # GET /documents
  # GET /documents.json
  def index
    @documents = Document.all
  end

  # GET /documents/1
  # GET /documents/1.json
  def show
		send_data(@document.file_contents,
					type: @document.content_type,
					filename: @document.filename)
  end

  # GET /documents/new
  def new
    @document = Document.new
  end

  # GET /documents/1/edit
  def edit
  end

  # POST /documents
  # POST /documents.json
  def create
    @document = Document.new(document_params)

    respond_to do |format|
      if @document.save
				# I personally added the redirect back to root url
        format.html { redirect_to root_url, notice: 'Document was successfully created.' }
        format.json { render :show, status: :created, location: @document }
      else
        format.html { render :new }
        format.json { render json: @document.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /documents/1
  # PATCH/PUT /documents/1.json
  def update
    respond_to do |format|
      if @document.update(document_params)
        format.html { redirect_to @document, notice: 'Document was successfully updated.' }
        format.json { render :show, status: :ok, location: @document }
      else
        format.html { render :edit }
        format.json { render json: @document.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /documents/1
  # DELETE /documents/1.json
  def destroy
    @document.destroy
    respond_to do |format|
      format.html { redirect_to documents_url, notice: 'Document was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_document
      @document = Document.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def document_params
      params.require(:document).permit(:filename, :content_type, :file_contents, :file)
			# Deviated from the aforementioned tutorial
    end
end

RailsNotes/Rails_Exploration/Completed/file_db_app/app/helpers/application_helper.rb
module ApplicationHelper
end

RailsNotes/Rails_Exploration/Completed/file_db_app/app/helpers/documents_helper.rb
module DocumentsHelper
end

RailsNotes/Rails_Exploration/Completed/file_db_app/app/views/documents/_form.html.erb
<%= form_for(document) do |f| %>
  <% if document.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(document.errors.count, "error") %> prohibited this document from being saved:</h2>

      <ul>
      <% document.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :filename %>
    <%= f.text_field :filename %>
  </div>

  <div class="field">
    <%= f.label :content_type %>
    <%= f.text_field :content_type %>
  </div>

  <div class="field">
    <%= f.label :file_contents %>
    <%= f.file_field :file %>
		<!-- This is a deviation from the tutorial  -->
		<!-- http://ryan.endacott.me/2014/06/10/rails-file-upload.html -->
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

RailsNotes/Rails_Exploration/Completed/file_db_app/app/views/documents/edit.html.erb
<h1>Editing Document</h1>

<%= render 'form', document: @document %>

<%= link_to 'Show', @document %> |
<%= link_to 'Back', documents_path %>

RailsNotes/Rails_Exploration/Completed/file_db_app/app/views/documents/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Documents</h1>

<table>
  <thead>
    <tr>
      <th>Filename</th>
      <th>Content type</th>
      <th>File contents</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @documents.each do |document| %>
      <tr>
        <td><%= document.filename %></td>
        <td><%= document.content_type %></td>
        <td><%= document.file_contents %></td>
        <td><%= link_to 'Show', document %></td>
        <td><%= link_to 'Edit', edit_document_path(document) %></td>
        <td><%= link_to 'Destroy', document, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Document', new_document_path %>

RailsNotes/Rails_Exploration/Completed/file_db_app/app/views/documents/new.html.erb
<h1>New Document</h1>

<%= render 'form', document: @document %>

<%= link_to 'Back', documents_path %>

RailsNotes/Rails_Exploration/Completed/file_db_app/app/views/documents/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Filename:</strong>
  <%= @document.filename %>
</p>

<p>
  <strong>Content type:</strong>
  <%= @document.content_type %>
</p>

<p>
  <strong>File contents:</strong>
  <%= @document.file_contents %>
</p>

<%= link_to 'Edit', edit_document_path(@document) %> |
<%= link_to 'Back', documents_path %>

RailsNotes/Rails_Exploration/Completed/file_db_app/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FileDbApp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>